# Generated by Django 5.0.4 on 2024-04-28 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0003_categorycolor_alter_note_options_alter_note_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.DeleteModel(
            name="CategoryColor",
        ),
    ]
